spring:
  ai:
    mcp:
      server:
        name: mcp-seal-generate-server
        version: 0.0.1
        type: SYNC
        stdio: true # Enable stdio transport
  # stdio
  main:
    web-application-type: none
    banner-mode: off